import { navBar } from "./components/navBar/navBar.js.js";
import { setBtnsListeners as navBarListeners } from "./components/navBar/btnInteraction.js.js";
import { pizzas } from "./components/pizzas/pizzas.js.js";
import { hamburguesas } from "./components/hamburgesas/hamburgesas.js.js";
let index = document.getElementById("index");
let pizzasNode = await pizzas();
let navBarNode = await navBar();
index.appendChild(pizzasNode);
index.appendChild(navBarNode);
navBarListeners();
